# Generated by Django 4.0.6 on 2022-07-21 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hab',
            name='creat_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
