# Generated by Django 4.0.6 on 2022-08-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HabCategory',
        ),
    ]
