# Generated by Django 4.0.6 on 2022-07-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_hab_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hab',
            name='author',
        ),
    ]
