# Generated by Django 4.0.6 on 2022-08-02 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_hab_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость комментария')),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hab', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.hab', verbose_name='HAB')),
            ],
        ),
    ]
