# Generated by Django 4.0.6 on 2022-08-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habuser',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='habuser',
            name='activation_key_expires',
        ),
        migrations.AlterField(
            model_name='habprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('W', 'Ж')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='habuser',
            name='role',
            field=models.CharField(choices=[('U', 'Зарегистрированный пользователь'), ('A', 'Администратор'), ('M', 'Модератор')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
