# Generated by Django 4.0.6 on 2022-08-06 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 10, 36, 20, 735472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='habuser',
            name='role',
            field=models.CharField(choices=[('M', 'Модератор'), ('A', 'Администратор'), ('U', 'Зарегистрированный пользователь')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
