# Generated by Django 4.0.6 on 2022-08-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habuser',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='habuser',
            name='activation_key_expires',
        ),
        migrations.AlterField(
            model_name='habuser',
            name='role',
            field=models.CharField(choices=[('M', 'Модератор'), ('A', 'Администратор'), ('U', 'Зарегистрированный пользователь')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
