# Generated by Django 3.2.8 on 2021-10-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users_avatars', verbose_name='картинка'),
        ),
    ]
