# Generated by Django 4.0.6 on 2022-08-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_habuser_activation_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('W', 'Ж'), ('M', 'M')], max_length=1, verbose_name='пол'),
        ),
    ]
