# Generated by Django 4.0.6 on 2022-08-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=512, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='Заголовок')),
                ('picture', models.ImageField(blank=True, upload_to='hab_picture', verbose_name='картинка')),
            ],
        ),
    ]
