# Generated by Django 4.0.6 on 2022-08-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_habprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('W', 'Ж')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='habuser',
            name='role',
            field=models.CharField(choices=[('A', 'Администратор'), ('U', 'Зарегистрированный пользователь'), ('M', 'Модератор')], default='U', max_length=1, verbose_name='роль'),
        ),
    ]
