# Generated by Django 4.0.6 on 2022-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_userhabs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhabs',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
