# Generated by Django 4.0.6 on 2022-08-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_userhabs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhabs',
            old_name='id',
            new_name='big_id',
        ),
    ]
