# Generated by Django 4.0.6 on 2022-08-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_rename_id_userhabs_big_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHabs',
        ),
    ]
